int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int rec_int(int n, int i);
int _sqrt_recursion(int n);
int is_prime_number(int n);
int rec_prime(int n, int i);
int is_palindrome(char *s);
int str_count(char *s);
int rec_pal(char *s, int len, int init);
